apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cpp-app
  template:
    metadata:
      labels:
        app: cpp-app
    spec:
      containers:
        - name: cpp-container
          image: cpp-project
          imagePullPolicy: IfNotPresent
          command: ["./app"]
